name: Maven

on:
  workflow_dispatch:

jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f
        with:
          maven-version: '3.8.7'
      - name: Configure Maven Settings
        uses: s4u/maven-settings-action@57c6d5534f446edc7261dca6261b88f2bf9c7934
