name: PowerShell

on:
  push:
  workflow_dispatch:

jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
      - name: Install Salesforce
        run: sh "npm install --global @salesforce/cli@2.5.8"

