name: PowerShell

on:
  push:
  workflow_dispatch:

jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: test
      - uses: actions/checkout@v4
        with:
          repository: hyperledger/fabric
          path: fabric
      - run: ls $GITHUB_WORKSPACE
