name: Maven

on:
  push:
  workflow_dispatch:

jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: self-hosted
    steps:
      - name: Install Docker
        run: |
          sudo dnf -y install dnf-plugins-core
          sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
