name: PowerShell

on:
  push:
  workflow_dispatch:

env:
  ProgressPreference: SilentlyContinue

jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
      # - name: INSTALL SFDX CLI
      #   run: |
      #     echo "Upgrading NPM"
      #     npm install -g npm
      - run: |
          node --version
          npm --version
          npm install -g npm
      - run: |
          echo "Installing sf"
          npm install --global --progress=false @salesforce/cli@2.5.8
      - run: |
          sf version --verbose --json
