name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  hosted:
    name: Demo Hosted Runners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
