name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: gh api /repos/lindluni/sandbox/actions/runs/${RUN_ID}/attempts/${RUN_ATTEMPT}/logs
        env:
          RUN_ID: ${{ github.run_id }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
