name: CI
on:
  workflow_dispatch:
jobs:
  matrix:
    runs-on: self-hosted
    steps:
      - uses: lindluni/setup-docker@group
        with:
          add-to-group: true
      - run: docker run -it -d ubuntu
