on: workflow_dispatch

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: event
        with:
          script: |
            return JSON.parse(JSON.stringify(repo))
          result-encoding: string
        env:
          repo: ${{ github.event.repository }}
      - run: echo "${{ steps.event.outputs.result }}"
